### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by n1ptune** [Cirn09/pintool3#1]
我在powershell里运行，相应文件也给了权限但还是报错不知道是怎么回事
```
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\code\pin_me\my_pin_tool\pintool3-master\pintool3-master\pintool3.py", line 94, in pin
    p = subprocess.run(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\pintool3.py", line 422, in <module>
    length = len_detect(cmd=arg.cmd,
  File ".\pintool3.py", line 289, in len_detect
    target = solve(cmd, inputs, arch, type, range_start, range_end, count_on,
  File ".\pintool3.py", line 237, in solve_multi
    pinfos = multipin(cmd, inputs, arch, range_start, range_end, count_on,
  File ".\pintool3.py", line 143, in multipin
    return [x.get() for x in r]
  File ".\pintool3.py", line 143, in <listcomp>
    return [x.get() for x in r]
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
PermissionError: [WinError 5] 拒绝访问。
```

**Comment by RevB3nd** [comment]
How to use this tool, the author did not introduce
